// catalog.js — documented Earth impacts + a few what-if NEOs.
// Preset parameters are illustrative assumptions, not calibrated reconstructions.
// craterKm records observed or reconstructed structure diameters (definitions vary).

export const ERA_LABELS = {
  witnessed: 'Witnessed',
  recent: 'Recent craters',
  cenozoic: 'Cenozoic',
  mesozoic: 'Age of dinosaurs',
  deep: 'Deep time',
  planetary: 'Giant / planetary',
};

export const ERA_ORDER = ['witnessed', 'recent', 'cenozoic', 'mesozoic', 'deep', 'planetary'];

/** Cities for “drop it here” events (Apophis, Bennu). */
export const CITIES = [
  { name: 'New York', lat: 40.71, lon: -74.01 },
  { name: 'Tokyo', lat: 35.68, lon: 139.69 },
  { name: 'London', lat: 51.51, lon: -0.13 },
  { name: 'Mumbai', lat: 19.08, lon: 72.88 },
  { name: 'Mexico City', lat: 19.43, lon: -99.13 },
  { name: 'Cairo', lat: 30.04, lon: 31.24 },
];

export const CATALOG = [
  {
    id: 'chelyabinsk',
    name: 'Chelyabinsk',
    era: 'witnessed',
    when: '15 Feb 2013',
    where: 'southern Urals, Russia',
    diameter: 20, comp: 'rock', velocity: 19000, angleDeg: 18,
    lat: 54.959, lon: 60.317, target: 'sedimentary',
    blurb: 'A 20 m chondrite broke up at ~30 km. The airburst injured ~1,500 people, mostly from glass. Best-documented fall on film.',
  },
  {
    id: 'tunguska',
    name: 'Tunguska',
    era: 'witnessed',
    when: '30 Jun 1908',
    where: 'Podkamennaya Tunguska, Siberia',
    diameter: 55, comp: 'rock', velocity: 15000, angleDeg: 35,
    lat: 60.886, lon: 101.894, target: 'sedimentary',
    blurb: 'Flattened 2,000 km² of taiga. No crater — the body burst in the air. Largest impact event in recorded history.',
  },
  {
    id: 'sikhote-alin',
    name: 'Sikhote-Alin',
    era: 'witnessed',
    when: '12 Feb 1947',
    where: 'Sikhote-Alin mountains, Russia',
    diameter: 10, comp: 'iron', velocity: 14000, angleDeg: 40,
    lat: 46.16, lon: 134.65, target: 'sedimentary', craterKm: 0.026,
    blurb: 'An iron meteoroid shattered in the lower atmosphere. Survivors punched a strewn field of pits — a rare iron fall on camera.',
  },
  {
    id: 'barringer',
    name: 'Barringer',
    era: 'recent',
    when: '~50,000 years ago',
    where: 'Arizona, USA',
    diameter: 50, comp: 'iron', velocity: 17000, angleDeg: 45,
    lat: 35.027, lon: -111.023, target: 'sedimentary', craterKm: 1.2,
    blurb: 'Meteor Crater. A 50 m iron made the textbook simple bowl — 1.2 km across, rim still sharp in the desert.',
  },
  {
    id: 'wolfe-creek',
    name: 'Wolfe Creek',
    era: 'recent',
    when: '~300,000 years ago',
    where: 'Western Australia',
    diameter: 15, comp: 'iron', velocity: 17000, angleDeg: 45,
    lat: -19.171, lon: 127.795, target: 'crystalline', craterKm: 0.88,
    blurb: 'One of the largest iron-meteorite craters on Earth. A round scar in the Tanami, with iron shale in the walls.',
  },
  {
    id: 'lonar',
    name: 'Lonar',
    era: 'recent',
    when: '~570,000 years ago',
    where: 'Maharashtra, India',
    diameter: 60, comp: 'rock', velocity: 20000, angleDeg: 45,
    lat: 19.977, lon: 76.508, target: 'crystalline', craterKm: 1.8,
    blurb: 'A young crater punched into Deccan basalt — rare on Earth. The lake inside is hypersaline and alkaline.',
  },
  {
    id: 'bosumtwi',
    name: 'Bosumtwi',
    era: 'cenozoic',
    when: '1.07 million years ago',
    where: 'Ashanti, Ghana',
    diameter: 800, comp: 'rock', velocity: 20000, angleDeg: 45,
    lat: 6.505, lon: -1.409, target: 'crystalline', craterKm: 10.5,
    blurb: 'West Africa’s youngest large crater. The lake holds a continuous climate record; tektites from the strike reached Ivory Coast.',
  },
  {
    id: 'eltanin',
    name: 'Eltanin',
    era: 'cenozoic',
    when: '2.5 million years ago',
    where: 'Bellingshausen Sea, Southern Ocean',
    diameter: 2000, comp: 'rock', velocity: 20000, angleDeg: 45,
    lat: -57.78, lon: -90.79, target: 'ocean',
    blurb: 'Evidence of a kilometre-scale deep-water impact in Southern Ocean sediments. The preset is illustrative; this simple model may predict a seafloor crater and does not reconstruct the observed event.',
  },
  {
    id: 'ries',
    name: 'Ries',
    era: 'cenozoic',
    when: '14.8 million years ago',
    where: 'Bavaria, Germany',
    diameter: 1500, comp: 'rock', velocity: 20000, angleDeg: 45,
    lat: 48.885, lon: 10.564, target: 'sedimentary', craterKm: 24,
    blurb: 'Nördlinger Ries. Moldavite tektites sprayed to Czechia. The medieval town of Nördlingen is built from suevite ejecta.',
  },
  {
    id: 'popigai',
    name: 'Popigai',
    era: 'cenozoic',
    when: '35.7 million years ago',
    where: 'Siberia, Russia',
    diameter: 5000, comp: 'rock', velocity: 20000, angleDeg: 45,
    lat: 71.65, lon: 111.18, target: 'crystalline', craterKm: 100,
    blurb: 'A 100 km crater that shock-converted graphite into diamonds. Same era as Chesapeake — a possible doublet in the late Eocene.',
  },
  {
    id: 'chesapeake',
    name: 'Chesapeake Bay',
    era: 'cenozoic',
    when: '35.5 million years ago',
    where: 'continental shelf off Virginia, USA',
    diameter: 3000, comp: 'rock', velocity: 20000, angleDeg: 45,
    lat: 37.285, lon: -76.013, target: 'shelf', craterKm: 85,
    blurb: 'Buried under the Bay. A wet-target crater ~85 km across; the hit helped set the shape of Chesapeake and local aquifers.',
  },
  {
    id: 'hiawatha',
    name: 'Hiawatha',
    era: 'cenozoic',
    when: '~58 million years ago',
    where: 'northwest Greenland',
    diameter: 1500, comp: 'iron', velocity: 20000, angleDeg: 45,
    lat: 78.72, lon: -66.18, target: 'crystalline', craterKm: 31,
    blurb: 'A buried Greenland crater dated to the Late Paleocene. The iron composition here is a scenario assumption.',
    sources: [{ label: 'Kenny et al. (2022)', url: 'https://doi.org/10.1126/sciadv.abm2434' }],
  },
  {
    id: 'chicxulub',
    name: 'Chicxulub',
    era: 'mesozoic',
    when: '66 million years ago',
    where: 'Yucatán, Mexico',
    diameter: 12000, comp: 'rock', velocity: 20000, angleDeg: 60,
    lat: 21.3, lon: -89.5, target: 'shelf', craterKm: 180,
    blurb: 'The K–Pg impactor. A ~12 km body into a shallow carbonate sea. Soot, sulfur, and a global winter ended the non-avian dinosaurs.',
  },
  {
    id: 'nadir',
    name: 'Nadir',
    era: 'mesozoic',
    when: '66 million years ago',
    where: 'Guinea Basin, off West Africa',
    diameter: 400, comp: 'rock', velocity: 20000, angleDeg: 45,
    lat: 9.39, lon: -17.09, target: 'ocean', waterDepth: 800, craterKm: 8.5,
    blurb: 'A buried marine structure near the K–Pg boundary. The inferred water depth at impact was about 800 m; a connection to Chicxulub is unproven.',
    sources: [{ label: 'Nicholson et al. (2024)', url: 'https://www.nature.com/articles/s43247-024-01700-4' }],
  },
  {
    id: 'manicouagan',
    name: 'Manicouagan',
    era: 'mesozoic',
    when: '214 million years ago',
    where: 'Québec, Canada',
    diameter: 5000, comp: 'rock', velocity: 20000, angleDeg: 45,
    lat: 51.38, lon: -68.7, target: 'crystalline', craterKm: 100,
    blurb: 'The “eye of Québec.” A late-Triassic 100 km crater, now an annular reservoir. Not the cause of the end-Triassic extinction.',
  },
  {
    id: 'morokweng',
    name: 'Morokweng',
    era: 'mesozoic',
    when: '145 million years ago',
    where: 'Kalahari, South Africa',
    diameter: 5000, comp: 'rock', velocity: 20000, angleDeg: 45,
    lat: -26.47, lon: 23.53, target: 'crystalline', craterKm: 70,
    blurb: 'Buried under Kalahari sand. Drill cores found fossil meteorite fragments — a ~70 km Jurassic–Cretaceous boundary crater.',
  },
  {
    id: 'sudbury',
    name: 'Sudbury',
    era: 'deep',
    when: '1.85 billion years ago',
    where: 'Ontario, Canada',
    diameter: 10000, comp: 'rock', velocity: 20000, angleDeg: 45,
    lat: 46.6, lon: -81.18, target: 'crystalline', craterKm: 130,
    blurb: 'One of Earth’s oldest large basins, later deformed. The melt sheet hosts world-class nickel–copper ores.',
  },
  {
    id: 'vredefort',
    name: 'Vredefort',
    era: 'deep',
    when: '2.02 billion years ago',
    where: 'Free State, South Africa',
    diameter: 15000, comp: 'rock', velocity: 20000, angleDeg: 45,
    lat: -26.86, lon: 27.47, target: 'crystalline', craterKm: 300,
    blurb: 'The largest confirmed crater on Earth — originally ~300 km. The Vredefort Dome is the eroded central uplift.',
  },
  {
    id: 'acraman',
    name: 'Acraman',
    era: 'deep',
    when: '~590 million years ago',
    where: 'Gawler Ranges, South Australia',
    diameter: 4000, comp: 'rock', velocity: 20000, angleDeg: 45,
    lat: -32.02, lon: 135.45, target: 'crystalline', craterKm: 90,
    blurb: 'Ejected debris is a marker bed in the Flinders Ranges, hundreds of kilometres away — a rare Ediacaran distal record.',
  },
  {
    id: 'apophis',
    name: 'Apophis',
    era: 'planetary',
    when: 'if it hit — 2029 is a flyby',
    where: 'pick a city',
    diameter: 370, comp: 'rock', velocity: 12600, angleDeg: 45,
    target: 'sedimentary', pickCity: true,
    blurb: '99942 Apophis, ~370 m. The 2029 encounter is a flyby. This preset assumes an impact speed and angle for a hypothetical comparison.',
  },
  {
    id: 'bennu',
    name: 'Bennu',
    era: 'planetary',
    when: 'hypothetical impact; not a predicted event',
    where: 'pick a city',
    diameter: 490, comp: 'porous', velocity: 12800, angleDeg: 45,
    target: 'sedimentary', pickCity: true,
    blurb: '101955 Bennu, the OSIRIS-REx rubble pile. NASA’s 2021 analysis estimated a cumulative impact probability of about 1 in 1,750 through 2300, not this century. This preset assumes an impact for comparison.',
    sources: [{ label: 'NASA/JPL (2021 orbit assessment)', url: 'https://www.jpl.nasa.gov/news/nasa-spacecraft-provides-insight-into-asteroid-bennus-future-orbit/' }],
  },
  {
    id: 'ceres',
    name: 'Ceres-size',
    era: 'planetary',
    when: 'hypothetical',
    where: 'Earth-size target',
    diameter: 940000, comp: 'rock', velocity: 15000, angleDeg: 45,
    blurb: 'A dwarf-planet-scale hit. Not a known terrestrial crater — a what-if at the edge of giant-impact physics.',
  },
  {
    id: 'moon',
    name: 'Moon-size',
    era: 'planetary',
    when: 'hypothetical',
    where: 'Earth-size target',
    diameter: 3474000, comp: 'rock', velocity: 12000, angleDeg: 45,
    blurb: 'A lunar-mass projectile. The remnant, melt, and spin sit in the Leinhardt–Stewart giant-impact regime.',
  },
  {
    id: 'theia',
    name: 'Theia (Moon-forming)',
    era: 'planetary',
    when: '~4.5 billion years ago',
    where: 'proto-Earth',
    diameter: 7420000, comp: 'rock', velocity: 10000, angleDeg: 45,
    blurb: 'An illustrative Mars-mass Theia scenario. Collision scaling suggests merging; disk mass, melting and subsequent moon formation are heuristic visualizations.',
  },
  {
    id: 'hit-and-run',
    name: 'Hit-and-run',
    era: 'planetary',
    when: 'hypothetical',
    where: 'Earth-size target',
    diameter: 6800000, comp: 'rock', velocity: 13000, angleDeg: 40,
    blurb: 'A fast, grazing giant impact. The projectile is stripped and escapes — the Genda–Kokubo–Ida hit-and-run branch.',
  },
];

export function eventById(id) {
  return CATALOG.find((e) => e.id === id);
}
