/** Generates the script for the launch-window / Δv-budget tool. */

export interface BudgetSpec {
  from: string;
  to: string;
  /** Parking orbit altitude at departure, km. */
  parkAlt: number;
  /** Capture periapsis altitude at arrival, km. Ignored for a flyby. */
  captureAlt: number;
  /** Capture orbit eccentricity (0 = circular); -1 means flyby (no capture burn). */
  captureEcc: number;
  /** ISO dates yyyy-mm-dd bounding the departure search. */
  dep: [string, string];
  /** Maximum time of flight, days. */
  maxTof: number;
  /** Grid points per axis. */
  n: number;
  /** Window tolerance: dates whose total Δv is within this fraction of the minimum count as "open". */
  tolerance: number;
  /** Margin applied to the burns (gravity losses, navigation), fraction. */
  margin: number;
  isp: number;
}

const jdCall = (iso: string): string => {
  const [y, m, d] = iso.split("-").map(Number);
  return `juliandate(${y}, ${m}, ${d})`;
};

export function budgetScript(s: BudgetSpec): string {
  const cap = (p: string) => p[0]!.toUpperCase() + p.slice(1);
  const flyby = s.captureEcc < 0;
  return `% Launch window and delta-v budget: ${cap(s.from)} -> ${cap(s.to)}, generated by the Budget tool
mu_dep = mu_${s.from};  r_park = R_${s.from} + ${s.parkAlt}e3;
mu_arr = mu_${s.to};    r_cap = R_${s.to} + ${s.captureAlt}e3;   e_cap = ${flyby ? 0 : s.captureEcc};
isp = ${s.isp};  margin = ${s.margin};  tol = ${s.tolerance};

jd_dep = linspace(${jdCall(s.dep[0])}, ${jdCall(s.dep[1])}, ${s.n});
jd_arr = linspace(jd_dep(1) + 30, jd_dep(end) + ${s.maxTof}, ${s.n});
p = porkchop('${s.from}', '${s.to}', jd_dep, jd_arr);

% Patched conics: burn out of the parking orbit, then capture at periapsis
dv_dep = escape_dv(p.vinf_dep * 1e3, r_park, mu_dep);
${flyby ? "dv_arr = zeros(size(dv_dep));                      % flyby: no capture burn" : "dv_arr = capture_dv(p.vinf_arr * 1e3, r_cap, mu_arr, e_cap);"}
dv_tot = (dv_dep + dv_arr) * (1 + margin);
dv_tot(p.tof > ${s.maxTof}) = NaN;                 % enforce the flight-time cap

[dv_min, k] = min(dv_tot(:));
[i, j] = ind2sub(size(dv_tot), k);
fprintf('=== Delta-v budget (%s -> %s) ===\\n', '${cap(s.from)}', '${cap(s.to)}');
fprintf('  depart %s   arrive %s   flight %d d\\n', datestr(jd_dep(j)), datestr(jd_arr(i)), round(p.tof(i, j)));
fprintf('  C3 = %.2f km^2/s^2   v-inf arrival = %.2f km/s\\n', p.C3(i, j), p.vinf_arr(i, j));
fprintf('  %-28s %8.0f m/s\\n', 'departure burn', dv_dep(i, j));
fprintf('  %-28s %8.0f m/s\\n', '${flyby ? "capture burn (flyby: none)" : "capture burn"}', dv_arr(i, j));
fprintf('  %-28s %8.0f m/s\\n', sprintf('margin (%.0f%%)', margin * 100), dv_min - dv_dep(i, j) - dv_arr(i, j));
fprintf('  %-28s %8.0f m/s\\n', 'TOTAL', dv_min);
fprintf('  propellant fraction at Isp %d s: %.1f%% (mass ratio %.2f)\\n', isp, 100 * prop_fraction(dv_min, isp), exp(dv_min / (isp * g0)));

% Launch window: departure dates whose best-case total is within tol of the minimum
best_per_day = min(dv_tot);                        % column-wise minimum over arrival dates
open_days = jd_dep(best_per_day <= dv_min * (1 + tol));
if isempty(open_days)
  disp('no departure date within tolerance');
else
  fprintf('=== Launch window (within %.0f%% of minimum) ===\\n', tol * 100);
  fprintf('  opens %s, closes %s: %d days\\n', datestr(open_days(1)), datestr(open_days(end)), round(open_days(end) - open_days(1)));
end

% Best total per departure date, with the window shaded by the tolerance line
plot(jd_dep - jd_dep(1), best_per_day / 1e3, 'b-'); hold on;
plot(jd_dep - jd_dep(1), ones(size(jd_dep)) * dv_min * (1 + tol) / 1e3, 'r--');
plot(jd_dep(j) - jd_dep(1), dv_min / 1e3, 'wo');
legend('best total dv', 'window threshold', 'minimum');
xlabel(['departure, days after ' datestr(jd_dep(1))]); ylabel('total dv (km/s)');
title('${cap(s.from)} to ${cap(s.to)}: launch window'); grid on;
% For the full departure x arrival map: contourf(jd_dep - jd_dep(1), jd_arr - jd_arr(1), dv_tot / 1e3, 12)
`;
}
