/** Generates the script the atmospheric-entry tool runs. */

export const ENTRY_BODIES = ["earth", "mars", "venus", "titan", "jupiter"] as const;

export interface EntrySpec {
  body: string;
  /** Entry speed, m/s. */
  v0: number;
  /** Flight-path angle, degrees (negative = descending). */
  gammaDeg: number;
  /** Entry interface altitude, km. */
  h0: number;
  mass: number;
  area: number;
  cd: number;
  ld: number;
  bankDeg: number;
  noseRadius: number;
  /** Stop altitude, km. */
  hStop: number;
  /** Stop speed, m/s. */
  vStop: number;
  plot: "hv" | "gt" | "qt" | "hr";
}

export const ENTRY_PRESETS: Record<string, Partial<EntrySpec> & { label: string }> = {
  apollo: { label: "Apollo lunar return (Earth)", body: "earth", v0: 11000, gammaDeg: -6.5, h0: 122, mass: 5500, area: 12, cd: 1.3, ld: 0.3, bankDeg: 60, noseRadius: 4.7, hStop: 0, vStop: 150 },
  soyuz: { label: "Soyuz ballistic from LEO (Earth)", body: "earth", v0: 7600, gammaDeg: -1.5, h0: 120, mass: 2900, area: 3.8, cd: 1.3, ld: 0, bankDeg: 0, noseRadius: 2.2, hStop: 0, vStop: 200 },
  msl: { label: "Curiosity / MSL (Mars)", body: "mars", v0: 5800, gammaDeg: -15.5, h0: 125, mass: 3300, area: 15.9, cd: 1.45, ld: 0.24, bankDeg: 0, noseRadius: 2.25, hStop: 0, vStop: 400 },
  huygens: { label: "Huygens probe (Titan)", body: "titan", v0: 6000, gammaDeg: -65, h0: 1270, mass: 320, area: 5.7, cd: 1.5, ld: 0, bankDeg: 0, noseRadius: 1.25, hStop: 0, vStop: 400 },
  galileo: { label: "Galileo probe (Jupiter)", body: "jupiter", v0: 47400, gammaDeg: -8.5, h0: 450, mass: 339, area: 1.27, cd: 1.05, ld: 0, bankDeg: 0, noseRadius: 0.22, hStop: -100, vStop: 1000 },
};

export function entryScript(s: EntrySpec): string {
  const cap = s.body[0]!.toUpperCase() + s.body.slice(1);
  const plots: Record<EntrySpec["plot"], string> = {
    hv: `plot(e.v / 1e3, e.h / 1e3, 'b-'); xlabel('speed (km/s)'); ylabel('altitude (km)'); title('${cap} entry: altitude vs speed');`,
    gt: `plot(e.t, e.decel / g0, 'r-'); xlabel('time (s)'); ylabel('deceleration (g)'); title('${cap} entry: g-load');`,
    qt: `plot(e.t, e.qdot / 1e4, 'r-'); hold on; plot(e.t, e.heat_load / 1e6, 'b--'); legend('heat flux (W/cm^2)', 'heat load (MJ/m^2)'); xlabel('time (s)'); title('${cap} entry: stagnation heating');`,
    hr: `plot(e.range / 1e3, e.h / 1e3, 'b-'); xlabel('downrange (km)'); ylabel('altitude (km)'); title('${cap} entry: trajectory');`,
  };
  return `% Atmospheric entry (${cap}), generated by the Entry tool
% Planar equations of motion over a non-rotating sphere with an exponential
% atmosphere, integrated by ode45; Sutton-Graves stagnation-point heating.
v0 = ${s.v0};                  % entry speed, m/s
gamma0 = deg2rad(${s.gammaDeg});   % flight-path angle (negative = down)
h0 = ${s.h0}e3;                % entry interface altitude, m
opts = struct('m', ${s.mass}, 'A', ${s.area}, 'CD', ${s.cd}, 'LD', ${s.ld}, 'bank', deg2rad(${s.bankDeg}), ...
              'rn', ${s.noseRadius}, 'h_stop', ${s.hStop}e3, 'v_stop', ${s.vStop});
e = entry('${s.body}', v0, gamma0, h0, opts);

fprintf('ballistic coefficient %.0f kg/m^2, L/D %.2f, bank %.0f deg\\n', e.beta, ${s.ld}, ${s.bankDeg});
fprintf('outcome: %s after %.0f s, %.0f km downrange\\n', e.outcome, e.t_end, e.range_end / 1e3);
fprintf('end state: h = %.1f km, v = %.0f m/s\\n', e.h_end / 1e3, e.v_end);
[gmax, k] = max(e.decel);
fprintf('peak deceleration %.1f g at t = %.0f s, h = %.1f km, v = %.2f km/s\\n', gmax / g0, e.t(k), e.h(k) / 1e3, e.v(k) / 1e3);
[qmax, k] = max(e.qdot);
fprintf('peak heat flux %.0f W/cm^2 at t = %.0f s, h = %.1f km; total heat load %.1f MJ/m^2\\n', ...
  qmax / 1e4, e.t(k), e.h(k) / 1e3, e.total_heat_load / 1e6);
[qd, k] = max(e.q);
fprintf('peak dynamic pressure %.1f kPa at h = %.1f km\\n', qd / 1e3, e.h(k) / 1e3);

${plots[s.plot]} grid on;
% Try: sweep gamma0 to find the skip-out / g-limit corridor, or set 'LD' to 0 for ballistic.
`;
}
