/** Generates the script for the gravity-assist / flyby tool. */

export interface FlybySpec {
  body: string;
  /** Flyby date, ISO yyyy-mm-dd (sets the planet's heliocentric state). */
  date: string;
  /** Inbound excess speed, km/s. */
  vinf: number;
  /** Angle of the inbound v∞ measured from the planet's velocity vector, degrees (0 = catching up from behind). */
  angleDeg: number;
  /** Periapsis altitude, km. */
  altitude: number;
  side: "trailing" | "leading";
  plot: "sweep" | "vectors";
}

const jdCall = (iso: string): string => {
  const [y, m, d] = iso.split("-").map(Number);
  return `juliandate(${y}, ${m}, ${d})`;
};

export function flybyScript(s: FlybySpec): string {
  const cap = s.body[0]!.toUpperCase() + s.body.slice(1);
  return `% Gravity assist at ${cap}, generated by the Flyby tool
mu = mu_${s.body};  R = R_${s.body};
jd = ${jdCall(s.date)};
[r_pl, v_pl] = ephemeris('${s.body}', jd);        % heliocentric state of the planet
rp = R + ${s.altitude}e3;                          % periapsis radius, m

% Inbound excess velocity: ${s.vinf} km/s at ${s.angleDeg} deg from the planet's velocity, in its orbital plane
vhat = v_pl / norm(v_pl);
hhat = cross(r_pl, v_pl); hhat = hhat / norm(hhat);
nhat = cross(hhat, vhat);                          % in-plane, roughly anti-radial
ang = deg2rad(${s.angleDeg});
vinf_in = ${s.vinf}e3 * (cos(ang) * vhat + sin(ang) * nhat);
nrm = ${s.side === "trailing" ? "" : "-"}cross(vinf_in, v_pl);    % flyby-plane normal, ${s.side}-side pass

f = flyby(vinf_in, rp, mu, nrm);
v_in = v_pl + vinf_in;  v_out = v_pl + f.vinf_out;
el_in = cart2kepler(r_pl, v_in, mu_sun);  el_out = cart2kepler(r_pl, v_out, mu_sun);

fprintf('%s flyby at %.0f km altitude, v-inf %.2f km/s\\n', '${cap}', (rp - R) / 1e3, norm(vinf_in) / 1e3);
fprintf('  turn angle %.1f deg (max %.1f deg at the surface), hyperbola e = %.3f, periapsis speed %.2f km/s\\n', ...
  rad2deg(f.delta), rad2deg(turn_angle(norm(vinf_in), R, mu)), f.e_hyp, f.v_p / 1e3);
fprintf('  heliocentric speed %.2f -> %.2f km/s (dv %.2f km/s, |dv vector| %.2f km/s)\\n', ...
  norm(v_in) / 1e3, norm(v_out) / 1e3, (norm(v_out) - norm(v_in)) / 1e3, f.dv_mag / 1e3);
fprintf('  orbit before: a = %.3f AU, e = %.3f, q = %.3f AU, Q = %s, period %s\\n', ...
  el_in(1) / AU, el_in(2), el_in(1) * (1 - el_in(2)) / AU, apo(el_in), per(el_in));
fprintf('  orbit after:  a = %.3f AU, e = %.3f, q = %.3f AU, Q = %s, period %s\\n', ...
  el_out(1) / AU, el_out(2), el_out(1) * (1 - el_out(2)) / AU, apo(el_out), per(el_out));
fprintf('  inclination change %.2f deg\\n', rad2deg(el_out(3) - el_in(3)));
${s.plot === "sweep" ? `
% Sweep the flyby altitude: energy gained versus closest approach
alts = logspace(log10(max(100e3, 0.02 * R)), log10(50 * R), 120);
dv = zeros(size(alts)); turn = zeros(size(alts));
for k = 1:numel(alts)
  fk = flyby(vinf_in, R + alts(k), mu, nrm);
  dv(k) = (norm(v_pl + fk.vinf_out) - norm(v_in)) / 1e3;
  turn(k) = rad2deg(fk.delta);
end
semilogx(alts / 1e3, dv, 'b-'); hold on; plot((rp - R) / 1e3, (norm(v_out) - norm(v_in)) / 1e3, 'wo');
xlabel('periapsis altitude (km)'); ylabel('heliocentric speed change (km/s)');
title('${cap} gravity assist: dv vs closest approach'); grid on;` : `
% Vector diagram in the planet's orbital plane (km/s): planet velocity, inbound and outbound heliocentric velocities
P = [vhat nhat]';                                    % 2-D basis: along-track, in-plane normal
vp2 = P * v_pl / 1e3; vi2 = P * v_in / 1e3; vo2 = P * v_out / 1e3;
plot([0 vp2(1)], [0 vp2(2)], 'k-'); hold on;
plot([0 vi2(1)], [0 vi2(2)], 'r-'); plot([0 vo2(1)], [0 vo2(2)], 'b-');
plot([vp2(1) vi2(1)], [vp2(2) vi2(2)], 'r--'); plot([vp2(1) vo2(1)], [vp2(2) vo2(2)], 'b--');
legend('planet', 'in (helio)', 'out (helio)', 'v-inf in', 'v-inf out');
axis equal; grid on; xlabel('along-track (km/s)'); ylabel('in-plane normal (km/s)');
title('${cap} flyby velocity triangle');`}

function s = apo(el)
  if el(2) < 1, s = sprintf('%.3f AU', el(1) * (1 + el(2)) / AU); else, s = 'escape'; end
end
function s = per(el)
  if el(2) < 1, s = sprintf('%.2f yr', period(el(1), mu_sun) / year); else, s = 'hyperbolic'; end
end
`;
}
