/** Generates the MATLAB-style script the Porkchop tool runs, so users can edit it afterwards. */

export const PLANETS = ["mercury", "venus", "earth", "mars", "jupiter", "saturn", "uranus", "neptune"] as const;

export interface PorkchopSpec {
  from: string;
  to: string;
  /** ISO dates yyyy-mm-dd. */
  dep: [string, string];
  arr: [string, string];
  n: number;
  what: "C3" | "vinf_arr" | "total";
  retro: boolean;
}

const jdCall = (iso: string): string => {
  const [y, m, d] = iso.split("-").map(Number);
  return `juliandate(${y}, ${m}, ${d})`;
};

export function porkchopScript(s: PorkchopSpec): string {
  const cap = (p: string) => p[0]!.toUpperCase() + p.slice(1);
  const quantity =
    s.what === "C3" ? { expr: "p.C3", label: "departure C3 (km^2/s^2)", levels: "[6 8 10 12 15 20 25 30 40 60 100]" }
    : s.what === "vinf_arr" ? { expr: "p.vinf_arr", label: "arrival v-infinity (km/s)", levels: "[2 2.5 3 3.5 4 5 6 8 10 15]" }
    : { expr: "p.C3 + p.vinf_arr.^2", label: "C3 + arrival v-inf^2 (km^2/s^2)", levels: "[15 20 25 30 40 50 60 80 100 150]" };
  return `% Porkchop plot: ${cap(s.from)} -> ${cap(s.to)}, generated by the Porkchop tool
jd_dep = linspace(${jdCall(s.dep[0])}, ${jdCall(s.dep[1])}, ${s.n});
jd_arr = linspace(${jdCall(s.arr[0])}, ${jdCall(s.arr[1])}, ${s.n});
p = porkchop('${s.from}', '${s.to}', jd_dep, jd_arr${s.retro ? ", 'retro'" : ""});

Z = ${quantity.expr};
[zmin, k] = min(Z(:));
[i, j] = ind2sub(size(Z), k);
fprintf('minimum ${quantity.label} = %.2f\\n', zmin);
fprintf('  depart %s, arrive %s, time of flight %d days\\n', datestr(jd_dep(j)), datestr(jd_arr(i)), round(jd_arr(i) - jd_dep(j)));
fprintf('  C3 there = %.2f km^2/s^2, arrival v-inf = %.2f km/s\\n', p.C3(i, j), p.vinf_arr(i, j));

contourf(jd_dep - jd_dep(1), jd_arr - jd_arr(1), Z, ${quantity.levels});
hold on;
plot(jd_dep(j) - jd_dep(1), jd_arr(i) - jd_arr(1), 'wo');
xlabel(['departure, days after ' datestr(jd_dep(1))]);
ylabel(['arrival, days after ' datestr(jd_arr(1))]);
title('${cap(s.from)} to ${cap(s.to)}: ${quantity.label}'); grid on;
`;
}
