/** Generates the script for the station-keeping / orbit-maintenance tool. */

export interface StationSpec {
  regime: "leo" | "geo";
  years: number;
  mass: number;
  isp: number;
  /** Burn margin as a fraction. */
  margin: number;
  plot: "sawtooth" | "sweep" | "lifetime";
  // LEO
  alt: number;
  inc: number;
  area: number;
  cd: number;
  activity: "low" | "mean" | "high";
  /** Tolerated altitude drop before a reboost, km. */
  deadband: number;
  // GEO
  lon: number;
  /** Longitude box half-width, deg. */
  box: number;
  year: number;
  srpArea: number;
  cr: number;
  /** Inclination box, deg. */
  ibox: number;
}

export function stationScript(s: StationSpec): string {
  return s.regime === "leo" ? leoScript(s) : geoScript(s);
}

function leoScript(s: StationSpec): string {
  const plots: Record<StationSpec["plot"], string> = {
    sawtooth: `
% Altitude history with the deadband strategy (analytic sawtooth from the reboost cycle)
Tc = rb.interval / f_rot / 86400;                 % reboost cycle, days
span = min(round(years * 365.25), max(30 * Tc, 10));   % ~30 cycles, capped at the mission
days = linspace(0, span, 1500);
hh = (h + dh) - dh * mod(days, Tc) / Tc;
plot(days, hh / 1e3, 'b-'); hold on;
plot(days, (h / 1e3) * ones(size(days)), 'r--'); plot(days, ((h + dh) / 1e3) * ones(size(days)), 'r--');
xlabel('days'); ylabel('altitude (km)');
title(sprintf('%d reboosts in %.2f yr (%.0f/yr), %.2f m/s each', floor(span / Tc), span / 365.25, rb.per_year * f_rot, rb.dv_reboost)); grid on;`,
    sweep: `
% Annual drag make-up dv versus altitude for this spacecraft and activity level
alts = linspace(min(250e3, h), max(1000e3, h), 160); dvs = zeros(size(alts));
for k = 1:numel(alts), dk = drag_decay(alts(k), m, A, CD, act); dvs(k) = dk.dv_year * f_rot; end
semilogy(alts / 1e3, dvs, 'b-'); hold on; semilogy(h / 1e3, dv_year, 'wo');
xlabel('altitude (km)'); ylabel('drag make-up dv (m/s per year)'); title(['annual dv, solar activity ' act]); grid on;`,
    lifetime: `
% Uncontrolled decay from the hold altitude (adaptive steps until 100 km or 30 years)
t = 0; hcur = h; tt = []; hh = [];
while hcur > 100e3 && t < 30 * 365.25
  tt(end + 1) = t; hh(end + 1) = hcur;
  dk = drag_decay(hcur, m, A, CD, act);
  step = min(30, 0.002 * hcur / max(1e-9, -dk.dadt * f_rot * 86400));   % adaptive day step
  hcur = hcur + dk.dadt * f_rot * 86400 * step; t = t + step;
end
tt(end + 1) = t; hh(end + 1) = hcur;
plot(tt / 365.25, hh / 1e3, 'b-'); xlabel('years'); ylabel('altitude (km)');
if hcur <= 100e3
  title(sprintf('uncontrolled decay: %.2f yr to 100 km', t / 365.25));
else
  title(sprintf('uncontrolled decay: %.0f km after %.1f yr (> 30 yr to 100 km)', hcur / 1e3, t / 365.25));
end
grid on;`,
  };
  return `% Orbit maintenance (LEO), generated by the Station-keeping tool
% Drag decay from Vallado's exponential atmosphere with a solar-activity knob,
% deadband reboosts, uncontrolled lifetime, J2 nodal drift and the propellant budget.
h = ${s.alt}e3;  inc = deg2rad(${s.inc});  act = '${s.activity}';
m = ${s.mass};  A = ${s.area};  CD = ${s.cd};        % mass, drag area, drag coefficient
dh = ${s.deadband}e3;                          % tolerated altitude drop before a reboost
years = ${s.years};  isp = ${s.isp};  margin = ${s.margin};

a = R_earth + h;  v = vcirc(a, mu_earth);  T = period(a, mu_earth);
f_rot = atm_rotation(h, inc);               % rotating atmosphere lowers drag for prograde orbits
d = drag_decay(h, m, A, CD, act);
rb = reboost(h + dh, dh, m, A, CD, act);
life = orbit_lifetime(h, m, A, CD, act) / f_rot;

fprintf('=== LEO maintenance at %.0f km, i = %.1f deg, solar activity %s ===\\n', h / 1e3, rad2deg(inc), act);
fprintf('  density %.3g kg/m^3, ballistic coefficient %.1f kg/m^2, rotation factor %.3f\\n', d.rho, d.beta, f_rot);
fprintf('  decay %.1f m/day (%.2f km/month), %.2f m per revolution\\n', -d.dadt * f_rot * 86400, -d.dadt * f_rot * 86400 * 30.4375 / 1e3, -d.da_rev * f_rot);
fprintf('  drag make-up: %.4f m/s per rev, %.1f m/s per year\\n', d.dv_rev * f_rot, d.dv_year * f_rot);
fprintf('  reboost every %.1f days: %.2f m/s per burn (%.1f burns/yr), %.1f m/s/yr\\n', rb.interval / f_rot / 86400, rb.dv_reboost, rb.per_year * f_rot, rb.dv_year * f_rot);
if life / (365.25 * 86400) < 100
  fprintf('  uncontrolled lifetime: %.2f years (%.0f days) to 100 km\\n', life / (365.25 * 86400), life / 86400);
else
  fprintf('  uncontrolled lifetime: > 100 years\\n');
end

j = j2_rates(a, 0, inc);
i_ss = sunsync_inc(a);
fprintf('  J2: node drift %.3f deg/day, perigee drift %.3f deg/day, nodal period %.2f min, %.3f rev/nodal day\\n', ...
  rad2deg(j.raan_dot) * 86400, rad2deg(j.argp_dot) * 86400, j.T_nodal / 60, j.revs_per_day);
if isnan(i_ss)
  fprintf('  no sun-synchronous inclination exists at this altitude\\n');
else
  fprintf('  sun-synchronous inclination at this altitude: %.2f deg (%s)\\n', rad2deg(i_ss), ...
    sprintf('%+.2f deg from yours', rad2deg(i_ss - inc)));
end

dv_year = rb.dv_year * f_rot;
b = mission_prop(m, dv_year, years, isp, margin);
fprintf('=== Budget: %.1f m/s/yr + %.0f%% margin over %g yr = %.0f m/s ===\\n', dv_year, margin * 100, years, b.dv_total);
fprintf('  propellant %.1f kg of %.0f kg (%.1f%%) at Isp %d s; first year %.1f kg\\n', b.propellant, m, 100 * b.propellant / m, isp, b.per_year(1));
fprintf('  reference: ISS-class 400 km needs 15-50 m/s/yr over a solar cycle; 700-800 km SSO drag < 1-2 m/s/yr\\n');
${plots[s.plot]}
`;
}

function geoScript(s: StationSpec): string {
  const plots: Record<StationSpec["plot"], string> = {
    sawtooth: `
% Longitude history: free-drift parabolas between east-west maneuvers over one year
acc = ew.accel * (86400^2) * (180/pi);          % deg/day^2 (positive = eastward)
Dd = usable;  Tc = ew.cycle / 86400;             % usable box half-width (deg), cycle (days)
days = 0 : 0.25 : 365.25; lonh = zeros(size(days));
if isinf(Tc)
  lonh = lon * ones(size(days));                 % equilibrium longitude: no drift
else
  for k = 1:numel(days)
    tau = mod(days(k), Tc) - Tc / 2;             % time relative to the turning point
    lonh(k) = lon - sign(acc) * Dd + 0.5 * acc * tau^2;   % parabola with vertex at the far edge
  end
end
plot(days, lonh, 'b-'); hold on;
plot(days, (lon + Dd) * ones(size(days)), 'r--'); plot(days, (lon - Dd) * ones(size(days)), 'r--');
xlabel('days'); ylabel('longitude (deg E)');
if isinf(Tc)
  title(sprintf('%s is an equilibrium longitude: no east-west maneuvers', lonstr(lon)));
else
  title(sprintf('E-W cycle %.1f d, %.3f m/s per maneuver', Tc, ew.dv_maneuver));
end
grid on;`,
    sweep: `
% Annual east-west dv versus station longitude, with the equilibrium points
lons = linspace(-180, 180, 361); dvs = zeros(size(lons));
for k = 1:numel(lons), dvs(k) = geo_ew(deg2rad(lons(k)), deg2rad(usable)).dv_year; end
plot(lons, dvs, 'b-'); hold on; plot(lon, ew.dv_year, 'wo');
plot(rad2deg(ew.stable), [0 0], 'g+'); plot(rad2deg(ew.unstable), [0 0], 'rx');
legend('E-W dv', 'this station', 'stable', 'unstable');
xlabel('longitude (deg E)'); ylabel('m/s per year'); title('triaxiality east-west dv'); grid on;`,
    lifetime: `
% Lunisolar inclination drift rate by year (18.6-year lunar nodal cycle) with the mission span
yrs = min(2000, year0) : max(2045, year0 + ceil(years)); rates = zeros(size(yrs));
for k = 1:numel(yrs), rates(k) = rad2deg(geo_inc_drift(juliandate(yrs(k), 7, 2)).total) * 365.25 * 86400; end
plot(yrs, rates, 'b-'); hold on;
plot([year0 year0 + years], [1 1] * mean_rate, 'r-');
legend('drift rate', 'mission mean');
xlabel('year'); ylabel('deg per year'); title('GEO inclination drift (vector sum of Sun and Moon)'); grid on;`,
  };
  return `% Station-keeping (GEO), generated by the Station-keeping tool
% North-south: lunisolar inclination drift (varies with the 18.6-yr lunar node).
% East-west: triaxiality (J22) longitude acceleration and a free-drift box cycle.
% Solar pressure sets a natural eccentricity that eats into the longitude box.
lon = ${s.lon};  box = ${s.box};  ibox = ${s.ibox};      % deg E, longitude half-width, inclination tolerance (deg)
year0 = ${s.year};  years = ${s.years};
m = ${s.mass};  A_sun = ${s.srpArea};  cr = ${s.cr};      % mass, sunlit area, reflectivity coefficient
isp = ${s.isp};  margin = ${s.margin};

jd0 = juliandate(year0, 7, 2);
% North-south: average the drift rate over the mission years
rates = zeros(1, max(1, ceil(years)));
for k = 1:numel(rates), rates(k) = geo_inc_drift(jd0 + (k - 1) * 365.25).total; end
mean_rate = rad2deg(mean(rates)) * 365.25 * 86400;   % deg/yr
ns = geo_ns(jd0, deg2rad(ibox));
dv_ns = v_geo * deg2rad(mean_rate);
% Cadence from the same mission-mean rate the budget uses, not the start-year rate.
ns_interval = 2 * ibox / mean_rate * 365.25;         % days between north-south burns
g0y = geo_inc_drift(jd0);

fprintf('=== GEO station-keeping at %s, %d to %g ===\\n', lonstr(lon), year0, year0 + years);
fprintf('  inclination drift %.3f deg/yr in %d (Sun %.3f + Moon %.3f), mission mean %.3f deg/yr\\n', ...
  rad2deg(g0y.total) * 365.25 * 86400, year0, rad2deg(g0y.sun) * 365.25 * 86400, rad2deg(g0y.moon) * 365.25 * 86400, mean_rate);
fprintf('  north-south: %.1f m/s/yr; with a %.2f deg tolerance, a %.2f m/s burn every %.1f days\\n', dv_ns, ibox, ns.dv_burn, ns_interval);

% Solar radiation pressure: the natural eccentricity swings longitude and eats into the box.
% Cap the swing at half the box, leaving the other half for drift control.
srp = geo_srp(cr, A_sun / m);
lib = rad2deg(srp.libration);
lib_hold = min(lib, box / 2);                       % swing actually tolerated
dv_e = srp.dv_cancel_year * (1 - lib_hold / lib);   % zero when the swing already fits
usable = box - lib_hold;                            % box left for east-west drift control

% East-west
ew = geo_ew(deg2rad(lon), deg2rad(usable));
fprintf('  longitude acceleration %+.5f deg/day^2 (stable points %s and %s)\\n', ...
  ew.accel * 86400^2 * 180 / pi, lonstr(rad2deg(ew.stable(1))), lonstr(rad2deg(ew.stable(2))));
if ew.dv_year > 0.01
  fprintf('  east-west: %.2f m/s/yr; %.4f m/s every %.1f days for a +/-%.3f deg usable box\\n', ew.dv_year, ew.dv_maneuver, ew.cycle / 86400, usable);
else
  fprintf('  east-west: at an equilibrium longitude, no drift control needed\\n');
end
if dv_e == 0
  fprintf('  SRP eccentricity %.2e swings longitude +/-%.3f deg: fits the box, +/-%.3f deg left for drift control\\n', srp.e_natural, lib, usable);
else
  fprintf('  SRP eccentricity %.2e swings longitude +/-%.3f deg: trim to +/-%.3f deg for %.2f m/s/yr\\n', srp.e_natural, lib, lib_hold, dv_e);
end

dv_year = dv_ns + ew.dv_year + dv_e;
b = mission_prop(m, dv_year, years, isp, margin);
fprintf('=== Budget: %.1f m/s/yr (N-S %.1f, E-W %.2f, ecc %.2f) + %.0f%% margin over %g yr = %.0f m/s ===\\n', ...
  dv_year, dv_ns, ew.dv_year, dv_e, margin * 100, years, b.dv_total);
fprintf('  propellant %.1f kg of %.0f kg (%.1f%%) at Isp %d s; first year %.1f kg, last year %.1f kg\\n', ...
  b.propellant, m, 100 * b.propellant / m, isp, b.per_year(1), b.per_year(end));
fprintf('  reference: GEO budgets are typically 45-55 m/s/yr, dominated by north-south control\\n');
${plots[s.plot]}

function s = lonstr(x)
  if x < 0, s = sprintf('%.1f W', -x); else, s = sprintf('%.1f E', x); end
end
`;
}
