/** Generates the script the Hohmann / bi-elliptic transfer planner runs. */

export const CENTRAL_BODIES = ["earth", "moon", "mars", "venus", "jupiter", "saturn", "sun"] as const;

export interface TransferSpec {
  body: string;
  /** "altitude" means r = R_body + value; "radius" means r = value. Values in km. */
  mode: "altitude" | "radius";
  r1: number;
  r2: number;
  /** Intermediate apoapsis for the bi-elliptic case, as a multiple of the larger circular radius. */
  ratio: number;
  /** Plane change between the orbits, degrees. */
  planeChangeDeg: number;
  plot: "dv" | "orbits";
}

export function transferScript(s: TransferSpec): string {
  const cap = s.body[0]!.toUpperCase() + s.body.slice(1);
  const r = (v: number) => (s.mode === "altitude" ? `R_${s.body} + ${v}e3` : `${v}e3`);
  return `% Hohmann vs bi-elliptic transfer planner (${cap}), generated by the Transfer tool
mu = mu_${s.body};
r1 = ${r(s.r1)};            % initial circular radius, m
r2 = ${r(s.r2)};            % final circular radius, m
ratio = ${s.ratio};          % bi-elliptic apoapsis as a multiple of max(r1, r2)
di = deg2rad(${s.planeChangeDeg});  % plane change between the orbits

h = hohmann(r1, r2, mu);
rB = ratio * max(r1, r2);
b = bielliptic(r1, r2, rB, mu);

% Plane change is cheapest at the slowest point: at apoapsis of the transfer
% (Hohmann) or at the intermediate apoapsis rB (bi-elliptic). Combine the
% burn vectorially: dv = sqrt(va^2 + vb^2 - 2 va vb cos di).
combine = @(va, vb, di) sqrt(va.^2 + vb.^2 - 2 .* va .* vb .* cos(di));
if r2 > r1
  v_arr_t = visviva(r2, h.a_transfer, mu);       % transfer speed at apoapsis
  h_dv2 = combine(v_arr_t, vcirc(r2, mu), di);   % circularise + plane change together
  h_total = h.dv1 + h_dv2;
else
  v_dep_t = visviva(r1, h.a_transfer, mu);
  h_dv1 = combine(vcirc(r1, mu), v_dep_t, di);   % plane change at the higher, slower orbit
  h_total = h_dv1 + h.dv2;
end
a1 = (r1 + rB) / 2; a2 = (rB + r2) / 2;
b_dv2 = combine(visviva(rB, a1, mu), visviva(rB, a2, mu), di);
b_total = b.dv1 + b_dv2 + b.dv3;

fprintf('%-14s %10s %10s %10s %10s %12s\\n', 'transfer', 'dv1 m/s', 'dv2 m/s', 'dv3 m/s', 'total m/s', 'time');
fprintf('%-14s %10.1f %10.1f %10s %10.1f %12s\\n', 'Hohmann', h.dv1, h.dv2, '-', h.dv_total, durationstr(h.tof));
fprintf('%-14s %10.1f %10.1f %10.1f %10.1f %12s\\n', 'bi-elliptic', b.dv1, b.dv2, b.dv3, b.dv_total, durationstr(b.tof));
if di > 0
  fprintf('with %.1f deg plane change: Hohmann %.1f m/s, bi-elliptic %.1f m/s\\n', rad2deg(di), h_total, b_total);
end
fprintf('radius ratio r2/r1 = %.2f (bi-elliptic wins for ratios above ~11.94 at large rB)\\n', r2 / r1);

% Sweep the intermediate apoapsis to find where bi-elliptic beats Hohmann
ratios = linspace(1, max(3, 3 * ratio), 200);
dv_be = zeros(size(ratios));
for k = 1:numel(ratios)
  bb = bielliptic(r1, r2, ratios(k) * max(r1, r2), mu);
  dv_be(k) = bb.dv_total;
end
[best_dv, kk] = min(dv_be);
fprintf('best bi-elliptic in sweep: %.1f m/s at rB = %.1f x max(r1,r2)\\n', best_dv, ratios(kk));
${s.plot === "dv" ? `
plot(ratios, dv_be / 1e3, 'b-'); hold on;
plot(ratios, ones(size(ratios)) * h.dv_total / 1e3, 'r--');
plot(ratio, b.dv_total / 1e3, 'wo');
legend('bi-elliptic', 'Hohmann', 'chosen rB');
xlabel('intermediate apoapsis / max(r1, r2)'); ylabel('total dv (km/s)');
title('${cap}: transfer dv'); grid on;` : `
% Orbit geometry (planar sketch, units of the initial radius)
th = linspace(0, 2*pi, 200);
plot(cos(th), sin(th), 'k-'); hold on;
plot(r2/r1 * cos(th), r2/r1 * sin(th), 'k-');
ht = linspace(0, pi, 100);
eh = abs(r2 - r1) / (r1 + r2);
ph = h.a_transfer / r1 * (1 - eh^2);
rh = ph ./ (1 + eh * cos(ht + pi * (r2 < r1)));
plot(rh .* cos(ht), rh .* sin(ht), 'r-');
e1 = (rB - r1) / (rB + r1); p1 = a1 / r1 * (1 - e1^2); rr1 = p1 ./ (1 + e1 * cos(ht));
plot(rr1 .* cos(ht), rr1 .* sin(ht), 'b-');
e2 = abs(rB - r2) / (rB + r2); p2 = a2 / r1 * (1 - e2^2); rr2 = p2 ./ (1 + e2 * cos(ht + pi));
plot(rr2 .* cos(ht), rr2 .* sin(ht), 'b--');
legend('r1', 'r2', 'Hohmann', 'bi-elliptic 1', 'bi-elliptic 2');
axis equal; grid on; title('${cap}: transfer geometry (r / r1)');`}

function s = durationstr(sec)
  if sec < 2 * 3600
    s = sprintf('%.1f min', sec / 60);
  elseif sec < 3 * 86400
    s = sprintf('%.2f h', sec / 3600);
  else
    s = sprintf('%.2f d', sec / 86400);
  end
end
`;
}
